[project]
name = "gender-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "flet>=0.25.2",
    "uvicorn>=0.34.0",
]
